import * as XLSX from 'xlsx';
import { spreadsheetColumns } from '../../constants/defaults';
import type { ImportError, ImportResult, SpreadsheetRow, Transaction } from '../../types';
import { parseCurrencyInput, parseDateInput } from '../formatters/formatters';
import { transactionSchema, transactionStatuses, transactionTypes, paymentMethods } from '../validation/schemas';

export type ColumnKey = (typeof spreadsheetColumns)[number];
export type ColumnMapping = Partial<Record<ColumnKey, string>>;
const synonyms: Record<ColumnKey, string[]> = {
  Data: ['data','emissao','emissão','lancamento','lançamento','dt'], Descrição: ['descricao','descrição','historico','histórico','detalhe','nome'], Tipo: ['tipo','natureza'], Categoria: ['categoria','grupo'], Subcategoria: ['subcategoria','sub grupo','subgrupo'], Valor: ['valor','preco','preço','total','vlr'], Conta: ['conta','banco','carteira'], 'Forma de pagamento': ['forma de pagamento','forma pagamento','pagamento','metodo','método'], Status: ['status','situacao','situação'], Parcela: ['parcela','n parcela'], 'Total de parcelas': ['total de parcelas','parcelas','qtd parcelas'], Vencimento: ['vencimento','data vencimento'], 'Pago em': ['pago em','pagamento em','data pagamento'], Observações: ['observacoes','observações','obs','nota'], 'ID externo': ['id externo','codigo','código','id']
};
const normalize = (v: string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
export function detectColumnMapping(headers: string[]): ColumnMapping { const mapping: ColumnMapping = {}; for (const col of spreadsheetColumns) { const candidates = [col, ...synonyms[col]].map(normalize); const found = headers.find(h => candidates.includes(normalize(h))); if (found) mapping[col] = found; } return mapping; }
export function suggestCategory(description: string, type: string): string { const s = normalize(description); if (type === 'Receita' && /salario|salário|ordenado/.test(s)) return 'Salário'; if (/uber|99|combustivel|combustível|metro|ônibus|onibus/.test(s)) return 'Transporte'; if (/mercado|supermercado|padaria|acougue/.test(s)) return 'Alimentação'; if (/farmacia|farmácia|medico|médico|hospital/.test(s)) return 'Saúde'; if (/netflix|spotify|prime|disney|assinatura/.test(s)) return 'Assinaturas'; return type === 'Receita' ? 'Renda extra' : 'Outros'; }
export async function readSpreadsheet(file: File): Promise<{ rows: SpreadsheetRow[]; headers: string[] }> { try { const buffer = await file.arrayBuffer(); const wb = XLSX.read(buffer, { type: 'array', cellDates: true }); const sheet = wb.Sheets[wb.SheetNames[0]]; if (!sheet) throw new Error('A planilha não possui abas com dados.'); const rows = XLSX.utils.sheet_to_json<SpreadsheetRow>(sheet, { defval: '' }); const headers = rows[0] ? Object.keys(rows[0]) : []; return { rows, headers }; } catch (e) { throw new Error(e instanceof Error ? `Falha de leitura do arquivo: ${e.message}` : 'Falha de leitura do Excel/CSV.'); } }
function enumValue<T extends readonly string[]>(value: unknown, allowed: T, fallback: T[number]): T[number] { const match = allowed.find(v => normalize(v) === normalize(String(value ?? ''))); return match ?? fallback; }
export function validateRows(rows: SpreadsheetRow[], mapping: ColumnMapping, existing: Transaction[] = []): ImportResult { const errors: ImportError[] = []; const duplicates: ImportError[] = []; const validRows: Transaction[] = []; let ignoredRows = 0; const required: ColumnKey[] = ['Data','Descrição','Tipo','Categoria','Valor','Conta','Forma de pagamento','Status']; required.forEach(c => { if (!mapping[c]) errors.push({ row: 0, field: c, message: `Coluna obrigatória ausente: ${c}`, severity: 'error' }); }); if (errors.some(e => e.row === 0)) return { validRows, errors, duplicates, ignoredRows, totalRows: rows.length };
  const seen = new Set(existing.map(t => t.externalId || `${t.date}-${normalize(t.description)}-${t.value}`));
  rows.forEach((row, index) => { const rowNumber = index + 2; const isEmpty = Object.values(row).every(v => String(v ?? '').trim() === ''); if (isEmpty) { ignoredRows++; return; } const get = (c: ColumnKey) => row[mapping[c] ?? c]; const date = parseDateInput(get('Data')); const dueDate = parseDateInput(get('Vencimento')) ?? undefined; const paidAt = parseDateInput(get('Pago em')) ?? undefined; const value = parseCurrencyInput(get('Valor')); const type = enumValue(get('Tipo'), transactionTypes, 'Despesa'); const status = enumValue(get('Status'), transactionStatuses, 'Pendente'); const paymentMethod = enumValue(get('Forma de pagamento'), paymentMethods, 'Pix'); const description = String(get('Descrição') ?? '').trim(); const category = String(get('Categoria') ?? '').trim() || suggestCategory(description, type); if (!date) errors.push({ row: rowNumber, field: 'Data', message: 'Data inválida. Use DD/MM/AAAA.', severity: 'error' }); if (!value || Number(value) <= 0) errors.push({ row: rowNumber, field: 'Valor', message: 'Valor inválido ou negativo indevido.', severity: 'error' }); if (!description) errors.push({ row: rowNumber, field: 'Descrição', message: 'Descrição obrigatória.', severity: 'error' }); if (!transactionTypes.includes(type)) errors.push({ row: rowNumber, field: 'Tipo', message: 'Tipo inválido.', severity: 'error' }); const now = new Date().toISOString(); const externalId = String(get('ID externo') ?? '').trim() || undefined; const dupKey = externalId || `${date}-${normalize(description)}-${value}`; if (seen.has(dupKey)) duplicates.push({ row: rowNumber, field: 'ID externo', message: 'Lançamento duplicado detectado e será ignorado.', severity: 'warning' }); if (errors.some(e => e.row === rowNumber) || seen.has(dupKey)) return; seen.add(dupKey); const transaction: Transaction = { id: crypto.randomUUID(), date: date!, description, type, category, subcategory: String(get('Subcategoria') ?? '').trim() || undefined, value: value!, account: String(get('Conta') ?? 'Banco').trim() || 'Banco', paymentMethod, status, installment: Number(get('Parcela') || 1), totalInstallments: Number(get('Total de parcelas') || 1), dueDate, paidAt, notes: String(get('Observações') ?? '').trim() || undefined, externalId, createdAt: now, updatedAt: now }; const parsed = transactionSchema.safeParse(transaction); if (parsed.success) validRows.push(transaction); else parsed.error.issues.forEach(issue => errors.push({ row: rowNumber, field: String(issue.path[0] ?? ''), message: issue.message, severity: 'error' })); }); return { validRows, errors, duplicates, ignoredRows, totalRows: rows.length }; }
export function buildTemplateWorkbook(): XLSX.WorkBook { const rows = [spreadsheetColumns, ['01/05/2026','Salário','Receita','Salário','Mensal','2500,00','Banco','Transferência','Pago',1,1,'01/05/2026','01/05/2026','Salário mensal','REC001'], ['02/05/2026','Mercado','Despesa','Alimentação','Supermercado','320,50','Cartão Nubank','Crédito','Pago',1,1,'10/06/2026','02/05/2026','Compra do mês','DES001'], ['03/05/2026','Internet','Despesa','Contas da casa','Internet','99,90','Banco','Pix','Pendente',1,1,'10/05/2026','','Conta mensal','DES002']]; const ws = XLSX.utils.aoa_to_sheet(rows); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Modelo'); return wb; }
