import Decimal from 'decimal.js';
import { endOfMonth, format, isBefore, parseISO, startOfMonth, subMonths } from 'date-fns';
import type { Budget, CreditCard, FinancialSummary, MonthlyReport, Transaction } from '../../types';

const d = (v: string | number) => new Decimal(v || 0);
const inRange = (date: string, start: Date, end: Date) => { const parsed = parseISO(date); return parsed >= start && parsed <= end; };
const isPaidCashAffecting = (t: Transaction, cashView: 'caixa' | 'competencia' = 'caixa') => t.status !== 'Cancelado' && (cashView === 'competencia' || t.status === 'Pago');
export function sumIncome(transactions: Transaction[], start?: Date, end?: Date): string { return transactions.filter(t => t.type === 'Receita' && isPaidCashAffecting(t) && (!start || inRange(t.date, start, end!))).reduce((acc,t)=>acc.plus(t.value), new Decimal(0)).toFixed(2); }
export function sumExpenses(transactions: Transaction[], start?: Date, end?: Date): string { return transactions.filter(t => t.type === 'Despesa' && isPaidCashAffecting(t) && (!start || inRange(t.date, start, end!))).reduce((acc,t)=>acc.plus(t.value), new Decimal(0)).toFixed(2); }
export function calculateBalance(transactions: Transaction[], initial = '0'): string { return transactions.filter(t => isPaidCashAffecting(t)).reduce((acc,t)=> t.type === 'Receita' ? acc.plus(t.value) : t.type === 'Despesa' ? acc.minus(t.value) : acc, d(initial)).toFixed(2); }
export function calculateSavingsRate(income: string, expenses: string): number { return d(income).eq(0) ? 0 : Math.max(0, d(income).minus(expenses).div(income).mul(100).toNumber()); }
export function categoryExpensePercentages(transactions: Transaction[]) { const total = d(sumExpenses(transactions)); const grouped = new Map<string, Decimal>(); transactions.filter(t=>t.type==='Despesa' && t.status !== 'Cancelado').forEach(t=>grouped.set(t.category, (grouped.get(t.category) ?? d(0)).plus(t.value))); return [...grouped].map(([category,value])=>({ category, value: value.toNumber(), percentage: total.eq(0) ? 0 : value.div(total).mul(100).toNumber() })).sort((a,b)=>b.value-a.value); }
export function calculateBudgetUsage(budget: Budget, transactions: Transaction[]): number { const spent = transactions.filter(t => t.type === 'Despesa' && t.category === budget.category && t.date.startsWith(budget.month)).reduce((a,t)=>a.plus(t.value), d(0)); return d(budget.limit).eq(0) ? 0 : spent.div(budget.limit).mul(100).toNumber(); }
export function monthlyEvolution(transactions: Transaction[], months = 6): MonthlyReport[] { return Array.from({ length: months }).map((_,i)=> subMonths(new Date(), months - i - 1)).map(monthDate => { const start = startOfMonth(monthDate); const end = endOfMonth(monthDate); const income = sumIncome(transactions,start,end); const expense = sumExpenses(transactions,start,end); return { month: format(monthDate,'MM/yyyy'), income, expense, net: d(income).minus(expense).toFixed(2), balance: calculateBalance(transactions.filter(t => parseISO(t.date) <= end)) }; }); }
export function futureInstallments(t: Transaction): Transaction[] { if (t.totalInstallments <= 1) return []; return Array.from({ length: t.totalInstallments - t.installment }, (_,i)=> ({ ...t, id: `${t.id}-p${t.installment+i+1}`, installment: t.installment+i+1, date: format(new Date(new Date(`${t.date}T00:00:00`).setMonth(new Date(`${t.date}T00:00:00`).getMonth()+i+1)), 'yyyy-MM-dd') })); }
export function creditCardInvoice(card: CreditCard, transactions: Transaction[], ref = new Date()) { const current = transactions.filter(t=>t.paymentMethod==='Crédito' && t.account===card.accountName && t.type==='Despesa' && t.status !== 'Cancelado').reduce((a,t)=>a.plus(t.value), d(0)); return { current: current.toFixed(2), future: transactions.filter(t=>t.paymentMethod==='Crédito' && parseISO(t.date)>ref).reduce((a,t)=>a.plus(t.value), d(0)).toFixed(2), usedLimitPercent: d(card.limit).eq(0) ? 0 : current.div(card.limit).mul(100).toNumber() }; }
export function pendingBills(transactions: Transaction[], today = new Date()) { return transactions.filter(t => t.status === 'Pendente').sort((a,b)=>(a.dueDate ?? a.date).localeCompare(b.dueDate ?? b.date)); }
export function overdueBills(transactions: Transaction[], today = new Date()) { return transactions.filter(t => t.status !== 'Pago' && t.status !== 'Cancelado' && t.dueDate && isBefore(parseISO(t.dueDate), today)); }
export function financialSummary(transactions: Transaction[]): FinancialSummary { const now = new Date(); const start = startOfMonth(now); const end = endOfMonth(now); const income = sumIncome(transactions,start,end); const expense = sumExpenses(transactions,start,end); const net = d(income).minus(expense).toFixed(2); const prevStart = startOfMonth(subMonths(now,1)); const prevEnd = endOfMonth(subMonths(now,1)); const prevNet = d(sumIncome(transactions,prevStart,prevEnd)).minus(sumExpenses(transactions,prevStart,prevEnd)).toFixed(2); const savingsRate = calculateSavingsRate(income,expense); return { balance: calculateBalance(transactions), monthlyIncome: income, monthlyExpense: expense, monthlyNet: net, savingsRate, healthScore: Math.min(100, Math.round(savingsRate * 1.5 + (d(net).gte(0) ? 35 : 10))), previousMonthNet: prevNet }; }
